apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playhive-minikube
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/tejubagalad/PlayHive.git"
    targetRevision: main
    path: "microservice-arch/yml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
