apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-orchestrator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-orchestrator
  template:
    metadata:
      labels:
        app: ai-orchestrator
    spec:
      containers:
        - name: ai-orchestrator
          image: tejubagalad/ai-orchestrator:latest
          imagePullPolicy: Always
          env:
            - name: PROMETHEUS_URL
              value: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
            - name: TARGET_POD_REGEX
              value: "gamehub-.*|snake-.*|game2048-.*"
            - name: WINDOW_MINUTES
              value: "10"
            - name: STEP_SECONDS
              value: "30"
            - name: PREDICTION_HORIZON_SEC
              value: "120"
            - name: CPU_THRESHOLD
              value: "20.0"
            - name: LOOP_INTERVAL_SEC
              value: "60"
